### ISSUE TITLE
EPIC Furthr goals

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/squid#18]
Focus on novel applications that are easy to deploy, not migrating existing ones

- [ ]  queue job server
- [ ] react app for running plans https://docs.deno.com/runtime/tutorials/how_to_with_npm/react/
      

  - [ ] i18 - alignment caching service
  - [ ] ViSR - [event-model](https://github.com/bluesky/event-model) subscription,
  - [ ]  h5web first

**Comment by stan-dot** [comment]
for event-model
https://chatgpt.com/c/66fbb276-61d8-8009-81b1-e8fc49d028ab

**Comment by stan-dot** [comment]
maybe at some point also 
- https://github.com/DiamondLightSource/pato-frontend
- https://github.com/DiamondLightSource/dedi-web
- https://github.com/DiamondLightSource/xas-standards-app
